### PR TITLE
Switch to github actions for CI + add CompatHelper

### LINKED ISSUE #49: Replace Travis CI by GitHub actions
Tends to be faster and simpler. Any objections?

### PR DESCRIPTION
**Pull request by carstenbauer**
Title says it all.

Closes #49

### CODE REVIEW

**Comment by carstenbauer** [comment]
Looks good to me. Don't know why AppVeyor is still running (I removed the yml file), perhaps it needs to be disabled explicity? Let's just merge this and take care of AppVeyor afterwards.

@eschnett Please merge if you agree.

**Comment by carstenbauer** [comment]
Oh, forgot to change the badges in the README. Will fix it in a second.

**Comment by carstenbauer** [comment]
One more thing to note: in the CI action I use / trigger codecov instead of coveralls. Haven't used the latter with gh actions before. So either we switch to codecov (my recommendation) or we need to figure this out.

**Comment by eschnett** [comment]
Let's switch, then. (I think the standard Julia Github actions support both.)

**Comment by carstenbauer** [comment]
Ok. We need to set the environmental variable in the repo settings (see https://app.codecov.io/gh/JuliaParallel/Hwloc.jl). I can't access them, I guess only owners can. I'll change the badge in the README. Let me know when you've set the env var.

**Comment by eschnett** [comment]
Which variable do I need to set where to what value? Do you have a pointer to instructions?

**Comment by carstenbauer** [comment]
I provided a link above but you might be logged in on codecov.io for it to work?

It tells me to set `CODECOV_TOKEN='272291c0-09f7-409e-a3e3-d56903a24ddc'`. In the repository "Settings", you need to add an environment under "Environments" (name it whatever you want, e.g. "env"). Then add an "Environment Secret" to this environment under "Secrets". That should be it (we might need to retriever CI in this PR).

Please also try to deactivate appveyor for this repo so that the single failing run goes away.

(PS: I think it's fine to share the token here, that is publicly. Worst case, someone pushes fake coverage data to codecov. Whatever 😄)

**Comment by eschnett** [comment]
I logged in, but I always ended up on a default page.

I added the secret. I re-configured Appveyor to stop building when no `appveyor.yml` file is present.

**Comment by carstenbauer** [comment]
Alright, looks good to me. It shows 74.4 % coverage for this PR (and nothing for master because codecov hasn't been triggered there yet).

I'd say we can merge this. Go ahead if you agree.

**Pull request merged**
