### PR TITLE
add windows Binaries provider

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like there's an InexactError somewhere on 32 bit. Note that `release` on Travis is still 0.3.x until the final tag of 0.4.0 is ready.

I can squash this if you'd prefer.

**Comment by eschnett** [comment]
The InexactError may be caused by a failure, which would then try to convert `typemax(Cuint)` to `Int`. I added an `@assert`.

I don't mind an unsquashed history.

**Comment by eschnett** [comment]
Can you rebase or merge the current master? If my guess is right, then there should now be an assertion error (with line number!) instead of an `InexactError`.

**Comment by tkelman** [comment]
done

**Comment by tkelman** [comment]
We have generic 32-bit Linux binaries which you could run in a virtualbox vm, that might be the fastest way for you to debug locally.

**Comment by eschnett** [comment]
This is about debugging a Windows issue. I haven't seen any problems on Linux.

**Comment by tkelman** [comment]
Many InexactErrors from conversion happen on both 32 bit linux and 32 bit windows. Not all, but I wouldn't think the code is very platform-dependent here?

**Pull request merged**
