### PR TITLE
Add AbstractTrees Interface

### PR DESCRIPTION
**Pull request by JBlaschke**
It exposes an `AbstractTrees.jl` interface via the `HwlocTreeNode`. Hwloc is already a tree, but it's not easy to use from Julia, so this makes things like tree traversal, and iteration, from Julia much easier.

This a follow-up for: https://github.com/JuliaParallel/Hwloc.jl/pull/71

### CODE REVIEW

**Review by carstenbauer — COMMENTED** [review]
Two comments from my side:

1) Sounds like a pretty good use case for a [Pkg Extension](https://pkgdocs.julialang.org/v1/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)): the tree functionality would only become automatically available when one loads both Hwloc and AbstractTrees in the same session. OTOH, AbstractTrees is very lightweight, e.g. doesn't have any dependencies, so it might be fine as is.

2) Needs documentation, at least an example of how to use it for the README.

**Comment by JBlaschke** [comment]
All done @carstenbauer  -- now using Pkg Extensions. And updated README. Should I merge?

**Comment by carstenbauer** [comment]
LGTM but since the README here contains the changes from PR #71 already I guess you should wait with merging until that one has landed.

BTW, I found a typo in the README: "eccident" should be "accident".

**Review by carstenbauer — APPROVED** [review]

**Comment by JBlaschke** [comment]
> LGTM but since the README here contains the changes from PR #71 already I guess you should wait with merging until that one has landed.

Yep. I'll wait for your approval on #71 and #72 and then merge both in that order

> BTW, I found a typo in the README: "eccident" should be "accident".

Fixed it! Thanks.

**Comment by carstenbauer** [comment]
I will merge this together with #71 in about 6 hours if there are no objections.

**Pull request merged**
